#pragma once
#include "NativeGameplayTags.h"

// Screen
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Screen_PressAnyKey);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Screen_MainMenu);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Screen_InGameHUD);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Screen_InGameMenu);

// 하위 태그
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Screen_InGameMenu_Trigger); // 선택
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Screen_InGameMenu_Block); // 막힌길
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Screen_InGameMenu_Map); // 지도열기

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Screen_InGameMenu_Transition); // 맵 바꾸기
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Screen_InGameMenu_TopMenu); // 지도열기 (Modal로 두기)

// Layers
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Main);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Overlay);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_Modal);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_Layer_HUD);
